project_id = "dewjhkgnoaepgkhulcbv"

[functions.get-google-credentials]
verify_jwt = false

[functions.notify-completion]
verify_jwt = false

[functions.get-visa-date]
verify_jwt = false

[functions.sync-visa-bulletin]
verify_jwt = false

[functions.provision-account]
verify_jwt = false

[functions.translate-evidence]
verify_jwt = false

[functions.client-file-ops]
verify_jwt = false
